// Code generated by protoc-gen-go. DO NOT EDIT.
// source: equipe.proto

package equipe

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Equipe struct {
	NomeEquipe           string   `protobuf:"bytes,1,opt,name=nomeEquipe,proto3" json:"nomeEquipe,omitempty"`
	NomeLider            string   `protobuf:"bytes,2,opt,name=nomeLider,proto3" json:"nomeLider,omitempty"`
	NumComponentes       int64    `protobuf:"varint,3,opt,name=numComponentes,proto3" json:"numComponentes,omitempty"`
	CorEquipe            string   `protobuf:"bytes,4,opt,name=corEquipe,proto3" json:"corEquipe,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Equipe) Reset()         { *m = Equipe{} }
func (m *Equipe) String() string { return proto.CompactTextString(m) }
func (*Equipe) ProtoMessage()    {}
func (*Equipe) Descriptor() ([]byte, []int) {
	return fileDescriptor_1522bebcec5c4cd5, []int{0}
}

func (m *Equipe) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Equipe.Unmarshal(m, b)
}
func (m *Equipe) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Equipe.Marshal(b, m, deterministic)
}
func (m *Equipe) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Equipe.Merge(m, src)
}
func (m *Equipe) XXX_Size() int {
	return xxx_messageInfo_Equipe.Size(m)
}
func (m *Equipe) XXX_DiscardUnknown() {
	xxx_messageInfo_Equipe.DiscardUnknown(m)
}

var xxx_messageInfo_Equipe proto.InternalMessageInfo

func (m *Equipe) GetNomeEquipe() string {
	if m != nil {
		return m.NomeEquipe
	}
	return ""
}

func (m *Equipe) GetNomeLider() string {
	if m != nil {
		return m.NomeLider
	}
	return ""
}

func (m *Equipe) GetNumComponentes() int64 {
	if m != nil {
		return m.NumComponentes
	}
	return 0
}

func (m *Equipe) GetCorEquipe() string {
	if m != nil {
		return m.CorEquipe
	}
	return ""
}

func init() {
	proto.RegisterType((*Equipe)(nil), "equipe.equipe")
}

func init() { proto.RegisterFile("equipe.proto", fileDescriptor_1522bebcec5c4cd5) }

var fileDescriptor_1522bebcec5c4cd5 = []byte{
	// 128 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0x2d, 0x2c, 0xcd,
	0x2c, 0x48, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0, 0x94, 0x7a, 0x18, 0xb9,
	0xa0, 0x4c, 0x21, 0x39, 0x2e, 0xae, 0xbc, 0xfc, 0xdc, 0x54, 0x57, 0x30, 0x4f, 0x82, 0x51, 0x81,
	0x51, 0x83, 0x33, 0x08, 0x49, 0x44, 0x48, 0x86, 0x8b, 0x13, 0xc4, 0xf3, 0xc9, 0x4c, 0x49, 0x2d,
	0x92, 0x60, 0x02, 0x4b, 0x23, 0x04, 0x84, 0xd4, 0xb8, 0xf8, 0xf2, 0x4a, 0x73, 0x9d, 0xf3, 0x73,
	0x0b, 0xf2, 0xf3, 0x52, 0xf3, 0x4a, 0x52, 0x8b, 0x25, 0x98, 0x15, 0x18, 0x35, 0x98, 0x83, 0xd0,
	0x44, 0x41, 0xa6, 0x24, 0xe7, 0x17, 0x41, 0x2d, 0x61, 0x81, 0x98, 0x02, 0x17, 0x48, 0x62, 0x03,
	0xbb, 0xce, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x29, 0x03, 0x04, 0x25, 0xad, 0x00, 0x00, 0x00,
}
